export const appContainerSelector = '#trello-app'
export const headerBarSelector = '.Nav'
export const trelloLogoSelector = '.Nav_logo'
export const loginButtonSelector = '[data-cy="login-menu"]'
export const bodyContainerSelector = '.background_container'
export const newBoardSelector = '#new-board'
export const boardInput = '[data-cy="new-board-input"]'
export const activeBoardSelector = '.board_newItem-active'
export const saveButton = '[data-cy="new-board-create"]'
export const boardContainer = '.boardDetail'
export const addListSelector = '[data-cy="add-list"]'
export const listInputSelector = '[data-cy="add-list-input"]'
export const saveButtonSelector = '[data-cy="save"]'
export const deleteButtonSelector = '[data-cy="delete"]'
export const dropdownButtonSelector = '[data-cy="list"] > .dropdown'
export const boardOptionsSelector = '[data-cy="board-options"]'
export const deleteBoardSelector = '.dropdown-content > .delete'
export const boardTitleSelector = '.background_title'

// login - sign up
export const logInSelector = '[data-cy="login-menu"]'
export const logInButtonSelector = '[data-cy="signup"]'
export const logInMessageSelector = '[id="loginMessage"]'
export const signUpButtonSelector = 'a:contains("Sign up here")'
export const signUpEmailSelector = '#signupEmail'
export const signUpPasswordSelector = '#signupPassword'
export const loggedUserSelector = '[data-cy="logged-user"]'
export const logOutButtonSelector = '#myDropdown >span:contains(Log out)'
